# Generated by Django 4.0.3 on 2022-07-08 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('project_name', models.CharField(max_length=200, verbose_name='Project name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('target_end', models.DateField(verbose_name='Target end date')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Actual end date')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('summary', models.CharField(max_length=255, verbose_name='Issue summary')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('identification_date', models.DateField(auto_now_add=True, verbose_name='Identified on')),
                ('priority', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('e', 'Extra')], default='m', max_length=1, verbose_name='Priority')),
                ('target_resolution', models.DateField(verbose_name='Planned resolution')),
                ('progress', models.TextField(null=True, verbose_name='Progress')),
                ('actual_resolution', models.DateField(blank=True, null=True, verbose_name='Actual resolution')),
                ('res_summary', models.TextField(blank=True, null=True, verbose_name='Resolution summary')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_solver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='troubleshooter', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='issues.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
